### ISSUE TITLE
[BUG] Blender output does not create a PNG

### ISSUE THREAD

**Issue by Informaticore** [INTI-CMNB/kicad_auto_test#1]
**Describe the bug**
Render Blender PNG is missing. In my yaml file I am using:

```
outputs:
  - name: 'Blender 3D Image'
    type: 'blender_export'
    dir: 'Generated/render'
    options:
      point_of_view:
        rotate_x: 45
        rotate_y: 45
        rotate_z: 75
      pcb3d:
        download: true
      render_options:
        samples: 100
        transparent_background: true
      outputs:
        type: render
```

the container I am using is: `container: ghcr.io/inti-cmnb/kicad7_auto_full:latest`

I have not touched the config since a while and with my commit some time ago it was generating that PNG

This job was running 3 weeks ago and the PNG was created: https://github.com/open-thngs/so-dimm-esp32-cm/actions/runs/5831095589

With this job today it did not generate the PNG: https://github.com/open-thngs/so-dimm-esp32-cm/actions/runs/6047189057/job/16410157210
